[package]
name = "markdown-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
ammonia = "=4.2.0"
markdown-engine = { path = "../markdown-engine" }
rustmark-core = { path = "../rustmark-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
