import {
  BookOpen,
  ChevronDown,
  ChevronRight,
  Code,
  Columns2,
  Download,
  File,
  FilePlus,
  FileText,
  FolderOpen,
  Save,
  Settings,
  Type,
  X,
  type LucideIcon,
} from "lucide-react";

export const glyphs = {
  new: FilePlus,
  file: File,
  folder: FolderOpen,
  save: Save,
  format: Type,
  export: Download,
  settings: Settings,
  close: X,
  markdown: FileText,
  split: Columns2,
  source: Code,
  read: BookOpen,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
} satisfies Record<string, LucideIcon>;
